version: '3'
services:
    dice_9_app:
        build: ./app/
        container_name: dice_9_app
        restart: always
        environment:
            - DATABASE_NAME=${DATABASE_NAME} #same as Database-container
            - DATABASE_USER=${DATABASE_USER} # Defined while creating Database-container
            - DATABASE_PASSWORD=${DATABASE_PASSWORD} # Defined while creating Database-container
            # This is needed for Flask-mail server
            - MAIL_USERNAME= ${MAIL_USERNAME}
            - MAIL_PASSWORD= ${MAIL_PASSWORD}
            - ENCRYPTION_KEY= ${ENCRYPTION_KEY}
        depends_on:
            - mysql_db

    nginx:
        build: ./other/nginx/
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        depends_on:
            - dice_9_app

    mysql_db:
        build: ./other/mysql_db/
        container_name: ${DATABASE_NAME}
        restart: always
        environment:
            MYSQL_DATABASE: 'users_dice9_'
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}